"""User role mapping done. table user and user_profile restructured.

Revision ID: 5547aa07e611
Revises: e0d5a6e4bb80
Create Date: 2026-07-26 22:33:36.954147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5547aa07e611'
down_revision: Union[str, Sequence[str], None] = 'e0d5a6e4bb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=False),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('address_line3', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('pin_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_city'), 'user_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_user_profiles_country'), 'user_profiles', ['country'], unique=False)
    op.create_index(op.f('ix_user_profiles_pin_code'), 'user_profiles', ['pin_code'], unique=False)
    op.create_index(op.f('ix_user_profiles_state'), 'user_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)

    # Data migration: carry firstname/lastname over into a profile row for each
    # existing user. address_line1/city/state/country/pin_code have no source
    # data on users, so they're backfilled with '' placeholders and left for
    # the user to fill in later.
    op.execute("""
        INSERT INTO user_profiles (
            id, first_name, last_name, user_id,
            address_line1, city, state, country, pin_code
        )
        SELECT
            gen_random_uuid(),
            COALESCE(firstname, ''),
            COALESCE(lastname, ''),
            id,
            '', '', '', '', ''
        FROM users
    """)

    # nullable=False with no default would fail against existing rows, so
    # backfill with a '' placeholder via server_default, then drop the
    # default so future inserts must supply a real value.
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=False, server_default=''))
    op.alter_column('users', 'phone_number', server_default=None)

    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_isActive'), 'users', ['isActive'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_unique_constraint('uq_user_email_phone', 'users', ['email', 'phone_number'])
    op.drop_column('users', 'userImage')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'avatarURL')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Added nullable first since existing rows have no value yet; backfilled
    # from user_profiles below, then constrained to NOT NULL to match the
    # original schema.
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatarURL', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('userImage', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.execute("""
        UPDATE users
        SET firstname = user_profiles.first_name,
            lastname = user_profiles.last_name
        FROM user_profiles
        WHERE user_profiles.user_id = users.id
    """)

    op.alter_column('users', 'firstname', nullable=False)
    op.alter_column('users', 'lastname', nullable=False)

    op.drop_constraint('uq_user_email_phone', 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_isActive'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_state'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_pin_code'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_country'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_city'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
