"""added userImage column

Revision ID: cb64f5652350
Revises: 1ea16d6252c3
Create Date: 2026-07-15 17:49:02.681290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb64f5652350'
down_revision: Union[str, Sequence[str], None] = '1ea16d6252c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userImage', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userImage')
    # ### end Alembic commands ###
